// more info about localization (plural, interpolation, etc.):
// https://phrase.com/blog/posts/react-native-i18n-with-expo-and-i18next-part-1/

const translations = {
    en: {
        signin: "Sign In",
        signin_screen: "Sign In Screen",
        signup: "Sign Up",
        signup_screen: "Sign Up Screen",
        enter_complete_name: "Please enter your full name",
        enter_email: "Please enter your email address",
        enter_valid_email: "Please fix email format",
        enter_valid_password: "Password must be at least 8 characters long",
        full_name: "Full Name",
        email: "Email",
        password: "Password",
        min_8_characters: "8 characters minimum",
        already_have_account: "Already have an account ?",
        forgot_password: "Forgot password ?",
        dont_have_account: "Don't have an account ?",
        formula: "Subscription",
        price: "Price",
        renewal: "Renewal on %{date}",
        formula_option: {
            free: "Free",
            silver: "Silver",
            gold: "Gold",
            platinum: "Platinum",
        },
        formula_descr: {
            limited_candidate: "Limited candidates",
            simple_profile: "Access to simple profile",
            full_profile: "Access to full profile",
            unlimited_candidate: "Unlimited candidates",
            messaging: "Access to messaging",
            job_offers: "Access to job offers",
        },
        price_formula: "%{price}€ / month",
        price_formula_free: "FREE",
        general: "General",
        company: "Company",
        my_information: "My information",
        disconnect: "Log out",
        home: "Home",
        offers: "Offers",
        account: "Account",
        chat: "Chat",
        review: "Review",
        jobName: "Job name",
        establishment: "Establishment",
        jobCategory: "Job category",
        perks: "Perks",
        salary: "Salary",
        startDate: "Start date",
        endDate: "End date",
        datePlaceholder: "dd/mm/yyyy",
        cancel: "Cancel",
        post: "Post",
        selectEstablishment: "Select an establishment",
        selectJobCategory: "Select a job category",
        my_offers: "My offers",
        sort: "Sort",
    },

    fr: {
        signin: "Se connecter",
        signin_screen: "Écran de connexion",
        signup: "S'inscrire",
        signup_screen: "Écran d'inscription",
        enter_complete_name: "Veuillez entrer votre nom complet",
        enter_email: "Veuillez entrer votre adresse e-mail",
        enter_valid_email: "Veuillez corriger le format d'email",
        enter_valid_password: "Le mot de passe doit contenir au moins 8 caractères",
        full_name: "Nom complet",
        email: "Adresse mail",
        password: "Mot de passe",
        min_8_characters: "8 caractères minimum",
        already_have_account: "Vous avez déjà un compte ?",
        forgot_password: "Mot de passe oublié ?",
        dont_have_account: "Vous n'avez pas de compte ?",
        formula: "Formule",
        price: "Prix",
        renewal: "Renouvellement le %{date}",
        formula_option: {
            free: "Gratuit",
            silver: "Argent",
            gold: "Or",
            platinum: "Platine",
        },
        formula_descr: {
            limited_candidate: "Candidats limité",
            simple_profile: "Accès profile simple",
            full_profile: "Accès profile complet",
            unlimited_candidate: "Candidats illimité",
            messaging: "Accès à la messagerie",
            job_offers: "Accès aux offres d'emploi",
        },
        price_formula: "%{price}€ / mois",
        price_formula_free: "GRATUIT",
        general: "Général",
        company: "Entreprise",
        my_information: "Mes informations",
        disconnect: "Se déconnecter",
        home: "Accueil",
        offers: "Offres",
        account: "Compte",
        chat: "Chat",
        review: "Avis",
        jobName: "Nom de l'emploi",
        establishment: "Établissement",
        jobCategory: "Catégorie d'emploi",
        perks: "Avantages",
        salary: "Salaire",
        startDate: "Date de début",
        endDate: "Date de fin",
        datePlaceholder: "jj/mm/aaaa",
        cancel: "Annuler",
        post: "Publier",
        selectEstablishment: "Sélectionner un établissement",
        selectJobCategory: "Sélectionner une catégorie d'emploi",
        my_offers: "Mes offres",
        sort: "Trier",
    },
}

export default translations;
