// more info about localization (plural, interpolation, etc.):
// https://phrase.com/blog/posts/react-native-i18n-with-expo-and-i18next-part-1/

const translations = {
    en: {
        signin: "Sign In",
        signin_screen: "Sign In Screen",
        signup: "Sign Up",
        signup_screen: "Sign Up Screen",
        enter_complete_name: "Please enter your full name",
        enter_email: "Please enter your email address",
        enter_valid_email: "Please fix email format",
        enter_valid_password: "Password must be at least 8 characters long",
        full_name: "Full Name",
        email: "Email",
        password: "Password",
        min_8_characters: "8 characters minimum",
        already_have_account: "Already have an account ?",
        forgot_password: "Forgot password ?",
        dont_have_account: "Don't have an account ?",
        formula: "Subscription",
        price: "Price",
        renewal: "Renewal on %{date}",
        formula_option: {
            free: "Free",
            silver: "Silver",
            gold: "Gold",
            platinum: "Platinum",
        },
        formula_descr: {
            limited_candidate: "Limited candidates",
            simple_profile: "Access to simple profile",
            full_profile: "Access to full profile",
            unlimited_candidate: "Unlimited candidates",
            messaging: "Access to messaging",
            job_offers: "Access to job offers",
        },
        price_formula: "%{price}€ / month",
        price_formula_free: "FREE",
        general: "General",
        company: "Company",
        my_information: "My information",
        disconnect: "Log out",
        home: "Home",
        offers: "Offers",
        account: "Account",
        chat: "Chat",
        review: "Review",
        jobName: "Job name",
        establishment: "Establishment",
        jobCategory: "Job category",
        perks: "Perks",
        salary: "Salary",
        startDate: "Start date",
        endDate: "End date",
        datePlaceholder: "dd/mm/yyyy",
        cancel: "Cancel",
        post: "Post",
        selectEstablishment: "Select an establishment",
        selectJobCategory: "Select a job category",
        my_offers: "My offers",
        numJobs: "%{numJobs} offers",
        sort: "Sort",
        my_establishments: "My establishments",
        employees: "Employees",
        past_offers: "Past",
        offers_associated_with_establishment: "Offers associated with this establishment",
        fulltime: "Full time",
        salaryPerMonth: "%{salary}€/month",
        match: {
            one: "%{count} match",
            other: "%{count} matches",
        },
        offer_details: "Offer details",
        edit: "Edit",
        delete: "Delete",
        note: "Note",
        title: "Title",
        comment: "Comment",
        textNote: {
            horrible:"Horrible",
            awful: "Awful",
            medium: "Medium",
            good: "Good",
            excellent: "Excellent",
        },
        errorInput: {
            required: "This field is required",
            length: "This field must be at least %{min} characters long",
        },
        hireCandidate: "Hire candidate",
        cancelHiring: "Cancel hiring",
        references: "References",
        experiences: "Experiences",
        reviews: "reviews",
        candidates: "Candidates",
    },

    fr: {
        signin: "Se connecter",
        signin_screen: "Écran de connexion",
        signup: "S'inscrire",
        signup_screen: "Écran d'inscription",
        enter_complete_name: "Veuillez entrer votre nom complet",
        enter_email: "Veuillez entrer votre adresse e-mail",
        enter_valid_email: "Veuillez corriger le format d'email",
        enter_valid_password: "Le mot de passe doit contenir au moins 8 caractères",
        full_name: "Nom complet",
        email: "Adresse mail",
        password: "Mot de passe",
        min_8_characters: "8 caractères minimum",
        already_have_account: "Vous avez déjà un compte ?",
        forgot_password: "Mot de passe oublié ?",
        dont_have_account: "Vous n'avez pas de compte ?",
        formula: "Formule",
        price: "Prix",
        renewal: "Renouvellement le %{date}",
        formula_option: {
            free: "Gratuit",
            silver: "Argent",
            gold: "Or",
            platinum: "Platine",
        },
        formula_descr: {
            limited_candidate: "Candidats limité",
            simple_profile: "Accès profile simple",
            full_profile: "Accès profile complet",
            unlimited_candidate: "Candidats illimité",
            messaging: "Accès à la messagerie",
            job_offers: "Accès aux offres d'emploi",
        },
        price_formula: "%{price}€ / mois",
        price_formula_free: "GRATUIT",
        general: "Général",
        company: "Entreprise",
        my_information: "Mes informations",
        disconnect: "Se déconnecter",
        home: "Accueil",
        offers: "Offres",
        account: "Compte",
        chat: "Chat",
        review: "Avis",
        jobName: "Nom de l'emploi",
        establishment: "Établissement",
        jobCategory: "Catégorie d'emploi",
        perks: "Avantages",
        salary: "Salaire",
        startDate: "Date de début",
        endDate: "Date de fin",
        datePlaceholder: "jj/mm/aaaa",
        cancel: "Annuler",
        post: "Publier",
        selectEstablishment: "Sélectionner un établissement",
        selectJobCategory: "Sélectionner une catégorie d'emploi",
        my_offers: "Mes offres",
        numJobs: "%{numJobs} offres",
        sort: "Trier",
        my_establishments: "Mes établissements",
        employees: "Employés",
        past_offers: "Passées",
        offers_associated_with_establishment: "Offres associées à cet établissement",
        fulltime: "Temps plein",
        salaryPerMonth: "%{salary}€/mois",
        match: {
            one: "%{count} match",
            other: "%{count} matches",
        },
        offer_details: "Détails de l'offre",
        edit: "Modifier",
        delete: "Supprimer",
        delete_confirm: "Confirmez-vous la suppression ?",
        note: "Note",
        title: "Titre",
        comment: "Commentaire",
        textNote: {

            horrible:"Horrible",
            awful: "Mauvais",
            medium: "Moyen",
            good: "Bon",
            excellent: "Excellent",
        },
        errorInput: {
            required: "Ce champ est requis",
            length: "Ce champ doit contenir au moins %{min} caractères",
        },
        hireCandidate: "Recruter le candidat",
        cancelHiring: "Annuler le recrutement",
        references: "Référents",
        experiences: "Expériences",
        reviews: "avis",
        candidates: "Candidats",
        ok: "OK",
        publishing_error: "Erreur lors de publication",
        phone: "Téléphone",
        firstname: "Prénom",
        lastname: "Nom",
    },
}

export default translations;
